/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;

/**
 *
 * @author luis_
 */
public class Tienda extends javax.swing.JFrame {
    
    private Inventario inventario;
    
    /**
     * Creates new form Tienda
     */
    public Tienda() {
        
        Vehiculo c = new Compacto (2015, "blanco", 400, "BMW", 200, 8, 8, 1.8);
        Vehiculo electrico = new Compacto(2019, "rojo", 800, "Tesla", 175, 5, 5);
        Vehiculo suv = new SUV(2010, "arena", 400, "Toyota", 150, 7, 8, 1.5);
        Vehiculo moto = new Moto(2015, "negra", 40, "Yamaha", 50, 5, 5, 1.5);
        Vehiculo pickup =new Pickup(2013, "gris", 500, "Jeep", 200, 8, 5, 1.8);
        Vehiculo deportivo = new Deportivo(2019, "gris", 1000, "McLaren", 300, 10, 10, 1.8);
        Vehiculo bla = new Compacto(2000, "amarillo", 50, "Volkswagen", 100, 5, 5, 1);
        Vehiculo mot = new Moto(2019,"naranja", 50, "Harley Davidson", 100, 5, 5, 1.5);
        Vehiculo carreras = new Deportivo(2019, "blanco", 10000, "Buggati", 400, 10, 10, 1.8);
        Vehiculo vocho = new Compacto(1975, "amarillo", 30, "Volkswagen", 80, 5, 5, 1);
        
        Vehiculo s = new SUV(2007, "gris", 50, "Honda", 140, 5, 5, 1.5);
        Vehiculo prius = new Compacto(2018, "blanco", 300, "Toyota", 160, 5, 5);
        Vehiculo civic = new Compacto(2018, "plata", 350, "Honda", 180, 8, 8, 1.5);
        Vehiculo l = new SUV(2018, "negro", 800, "Land Rover", 150, 8, 8, 1.5);
        Vehiculo grande = new Pickup(2015, "blanca", 200, "Ford", 200, 8, 8, 1.5);
        Vehiculo m = new Moto(2008, "negra", 15, "Yamaha", 75, 5, 5, 1.5);
        Vehiculo mo = new Moto(2009, "amarilla", 10, "Italika", 70, 5, 5, 1.5);
        Vehiculo cam = new SUV(2015, "negra", 180, "Dodge", 150, 8, 8, 1.5);
        
        inventario = new Inventario();
        
        try{
            inventario.comprarVehiculo(c);
            inventario.comprarVehiculo(electrico);
            inventario.comprarVehiculo(suv);
            inventario.comprarVehiculo(moto);
            inventario.comprarVehiculo(pickup);
            inventario.comprarVehiculo(deportivo);
            inventario.comprarVehiculo(bla);
            inventario.comprarVehiculo(mot);
            inventario.comprarVehiculo(carreras);
            inventario.comprarVehiculo(vocho);
            inventario.comprarVehiculo(s);
            inventario.comprarVehiculo(prius);
            inventario.comprarVehiculo(civic);
            inventario.comprarVehiculo(l);
            inventario.comprarVehiculo(grande);
            inventario.comprarVehiculo(m);
            inventario.comprarVehiculo(mo);
            inventario.comprarVehiculo(cam);
        }catch(FullInventoryException f){
            System.out.println("El inventario está lleno");
        }
        
        
        initComponents();
        
        VehiculoBox.removeAllItems();
        VehiculoBox.addItem("Compacto");
        VehiculoBox.addItem("Deportivo");
        VehiculoBox.addItem("Moto");
        VehiculoBox.addItem("SUV");
        VehiculoBox.addItem("Pickup");

        
        
        VehiculosButton.setEnabled(false);
        javax.swing.JPanel container = new javax.swing.JPanel();
        container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.Y_AXIS));
        ListaVehiculos.getViewport().setView(container);
        ExcepcionesLabel.setVisible(false);
        MarcaTextField.setVisible(false);
        ModeloTextField.setVisible(false);
        PrecioTextField.setVisible(false);
        RealizarButton.setVisible(false);
        TipoLabel.setVisible(false);
        VehiculoBox.setVisible(false);
        ColorTextField.setVisible(false);
        signoPrecio.setVisible(false);
        
        
        
        showVehiculos(inventario.getVehiculos());
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    private void showVehiculos(Vehiculo[] vehiculos){
        javax.swing.JPanel view = (javax.swing.JPanel)ListaVehiculos.getViewport().getView();
        view.removeAll();
        for(Vehiculo vehiculo: vehiculos){
            if(vehiculo != null){
                javax.swing.JLabel label = new javax.swing.JLabel();
                label.setText(vehiculo.toString());
                view.add(label);
            }
        }
        
        ListaVehiculos.revalidate();
        ListaVehiculos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ListaVehiculos = new javax.swing.JScrollPane();
        CatalogoLabel = new javax.swing.JLabel();
        VehiculosButton = new javax.swing.JButton();
        CamionetasButton = new javax.swing.JButton();
        MotosButton = new javax.swing.JButton();
        CarrosButton = new javax.swing.JButton();
        VehiculoBox = new javax.swing.JComboBox<>();
        TipoLabel = new javax.swing.JLabel();
        MarcaTextField = new javax.swing.JTextField();
        ModeloTextField = new javax.swing.JTextField();
        ColorTextField = new javax.swing.JTextField();
        PrecioTextField = new javax.swing.JTextField();
        ExcepcionesLabel = new javax.swing.JLabel();
        RealizarButton = new javax.swing.JButton();
        VenderToggle = new javax.swing.JToggleButton();
        ComprarToggle = new javax.swing.JToggleButton();
        signoPrecio = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CatalogoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CatalogoLabel.setText("Cátalogo de Vehículos");

        VehiculosButton.setText("Todos los Vehículos");
        VehiculosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehiculosButtonActionPerformed(evt);
            }
        });

        CamionetasButton.setText("Camionetas");
        CamionetasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamionetasButtonActionPerformed(evt);
            }
        });

        MotosButton.setText("Motos");
        MotosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotosButtonActionPerformed(evt);
            }
        });

        CarrosButton.setText("Carros");
        CarrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrosButtonActionPerformed(evt);
            }
        });

        VehiculoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TipoLabel.setText("Tipo de Vehículo:");

        MarcaTextField.setText("Marca");

        ModeloTextField.setText("Modelo (año)");
        ModeloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloTextFieldActionPerformed(evt);
            }
        });

        ColorTextField.setText("Color");
        ColorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorTextFieldActionPerformed(evt);
            }
        });

        PrecioTextField.setText("Precio (en miles de pesos)");
        PrecioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioTextFieldActionPerformed(evt);
            }
        });

        RealizarButton.setText("Realizar");
        RealizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarButtonActionPerformed(evt);
            }
        });

        VenderToggle.setText("Vender");
        VenderToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderToggleActionPerformed(evt);
            }
        });

        ComprarToggle.setText("Comprar");
        ComprarToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarToggleActionPerformed(evt);
            }
        });

        signoPrecio.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CatalogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComprarToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CamionetasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VehiculosButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VenderToggle, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(MotosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CarrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TipoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VehiculoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ExcepcionesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(MarcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModeloTextField)
                        .addGap(10, 10, 10)
                        .addComponent(ColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(signoPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PrecioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RealizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CatalogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehiculosButton)
                    .addComponent(CarrosButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MotosButton)
                    .addComponent(CamionetasButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComprarToggle)
                    .addComponent(VenderToggle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehiculoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MarcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RealizarButton)
                    .addComponent(signoPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExcepcionesLabel)
                .addGap(0, 32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(ListaVehiculos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VehiculosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehiculosButtonActionPerformed
        CarrosButton.setEnabled(true);
        CamionetasButton.setEnabled(true);
        MotosButton.setEnabled(true);
        VehiculosButton.setEnabled(false);
        showVehiculos(inventario.getVehiculos());
    }//GEN-LAST:event_VehiculosButtonActionPerformed

    private void CarrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrosButtonActionPerformed
        CarrosButton.setEnabled(false);
        CamionetasButton.setEnabled(true);
        MotosButton.setEnabled(true);
        VehiculosButton.setEnabled(true);
        showVehiculos(inventario.getCarros());
    }//GEN-LAST:event_CarrosButtonActionPerformed

    private void CamionetasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamionetasButtonActionPerformed
        CarrosButton.setEnabled(true);
        CamionetasButton.setEnabled(false);
        MotosButton.setEnabled(true);
        VehiculosButton.setEnabled(true);
        showVehiculos(inventario.getCamionetas());
    }//GEN-LAST:event_CamionetasButtonActionPerformed

    private void MotosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotosButtonActionPerformed
        CarrosButton.setEnabled(true);
        CamionetasButton.setEnabled(true);
        MotosButton.setEnabled(false);
        VehiculosButton.setEnabled(true);
        showVehiculos(inventario.getMotos());
    }//GEN-LAST:event_MotosButtonActionPerformed

    private void ModeloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeloTextFieldActionPerformed

    private void ColorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorTextFieldActionPerformed

    private void PrecioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioTextFieldActionPerformed

    private void VenderToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderToggleActionPerformed
        ExcepcionesLabel.setText("");
        ExcepcionesLabel.setVisible(true);
        MarcaTextField.setVisible(true);
        ModeloTextField.setVisible(true);
        PrecioTextField.setVisible(true);
        RealizarButton.setVisible(true);
        TipoLabel.setVisible(false);
        VehiculoBox.setVisible(false);
        ColorTextField.setVisible(true);
        signoPrecio.setVisible(true);
        ComprarToggle.setSelected(false);
    }//GEN-LAST:event_VenderToggleActionPerformed

    private void ComprarToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarToggleActionPerformed
        ExcepcionesLabel.setText("");
        ExcepcionesLabel.setVisible(true);
        MarcaTextField.setVisible(true);
        ModeloTextField.setVisible(true);
        PrecioTextField.setVisible(true);
        RealizarButton.setVisible(true);
        TipoLabel.setVisible(true);
        VehiculoBox.setVisible(true);
        ColorTextField.setVisible(true);
        signoPrecio.setVisible(true);
        VenderToggle.setSelected(false);
    }//GEN-LAST:event_ComprarToggleActionPerformed

    private void RealizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarButtonActionPerformed
    if (MarcaTextField.getText().equals("Marca") && ColorTextField.getText().equals("Color")){  
        ExcepcionesLabel.setText("Favor de llenar todos los campos");
    }  else{
        if(VenderToggle.isSelected()){
            try{
                inventario.venderVehiculo(Integer.parseInt(ModeloTextField.getText()), MarcaTextField.getText(), ColorTextField.getText(), Double.parseDouble(PrecioTextField.getText()));
                showVehiculos(inventario.getVehiculos());
                ExcepcionesLabel.setText("Vehículo vendido exitosamente");
                ModeloTextField.setText("Modelo (año)");
                PrecioTextField.setText("Precio (en miles de pesos)");
                ColorTextField.setText("Color");
                MarcaTextField.setText("Marca");
            } catch (NumberFormatException nf) {
                ExcepcionesLabel.setText("Favor de llenar todos los campos");
            } catch (EmptyInventoryException e){
                ExcepcionesLabel.setText(e.getMessage());
            } catch (IllegalArgumentException i){
                ExcepcionesLabel.setText("El vehículo no se encuentra en el inventario");
            } catch (NullPointerException n){
                ExcepcionesLabel.setText("El vehículo no existe");
            } 
        } else if (ComprarToggle.isSelected()){
            String tipo = (String)VehiculoBox.getSelectedItem();
            try{
                inventario.comprarVehiculo(tipo, Integer.parseInt(ModeloTextField.getText()), MarcaTextField.getText(), ColorTextField.getText(), Double.parseDouble(PrecioTextField.getText()));
                showVehiculos(inventario.getVehiculos());
                ExcepcionesLabel.setText("Vehículo comprado exitosamente");
                ModeloTextField.setText("Modelo (año)");
                PrecioTextField.setText("Precio (en miles de pesos)");
                ColorTextField.setText("Color");
                MarcaTextField.setText("Marca");
            } catch (NumberFormatException nf) {
                ExcepcionesLabel.setText("Favor de llenar todos los campos");
            } catch (FullInventoryException e){
                ExcepcionesLabel.setText(e.getMessage());
            } catch (IllegalArgumentException i){
                ExcepcionesLabel.setText("El modelo tiene que estar en el rango 1970-2019");
            } catch (NullPointerException n){
                ExcepcionesLabel.setText("El vehículo no existe");
            } 

        } else {
            ExcepcionesLabel.setText("Favor de seleccionar si desea comprar o vender");
        }
        
    
    }
    }//GEN-LAST:event_RealizarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CamionetasButton;
    private javax.swing.JButton CarrosButton;
    private javax.swing.JLabel CatalogoLabel;
    private javax.swing.JTextField ColorTextField;
    private javax.swing.JToggleButton ComprarToggle;
    private javax.swing.JLabel ExcepcionesLabel;
    private javax.swing.JScrollPane ListaVehiculos;
    private javax.swing.JTextField MarcaTextField;
    private javax.swing.JTextField ModeloTextField;
    private javax.swing.JButton MotosButton;
    private javax.swing.JTextField PrecioTextField;
    private javax.swing.JButton RealizarButton;
    private javax.swing.JLabel TipoLabel;
    private javax.swing.JComboBox<String> VehiculoBox;
    private javax.swing.JButton VehiculosButton;
    private javax.swing.JToggleButton VenderToggle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel signoPrecio;
    // End of variables declaration//GEN-END:variables
}
